// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJJcaayEcOqR6LuoD8hn4B590byYVJdv0',
    appId: '1:416175352696:web:f62e3151a23fb4a770768d',
    messagingSenderId: '416175352696',
    projectId: 'smart-ride-app-c77ee',
    authDomain: 'smart-ride-app-c77ee.firebaseapp.com',
    storageBucket: 'smart-ride-app-c77ee.firebasestorage.app',
    measurementId: 'G-4XN0QKMFS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUQLrAu4JUfdB-Kra1OApsl3J3i_TpZWk',
    appId: '1:416175352696:android:d0d79bd447a924e970768d',
    messagingSenderId: '416175352696',
    projectId: 'smart-ride-app-c77ee',
    storageBucket: 'smart-ride-app-c77ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBfcMrwEusSpkKfUWdtU4txLovdTmJ9H0',
    appId: '1:416175352696:ios:9458a3900d2fb51970768d',
    messagingSenderId: '416175352696',
    projectId: 'smart-ride-app-c77ee',
    storageBucket: 'smart-ride-app-c77ee.firebasestorage.app',
    iosBundleId: 'com.smartride.smartRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBfcMrwEusSpkKfUWdtU4txLovdTmJ9H0',
    appId: '1:416175352696:ios:87d67f84d033c35670768d',
    messagingSenderId: '416175352696',
    projectId: 'smart-ride-app-c77ee',
    storageBucket: 'smart-ride-app-c77ee.firebasestorage.app',
    iosBundleId: 'com.example.smartRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJJcaayEcOqR6LuoD8hn4B590byYVJdv0',
    appId: '1:416175352696:web:34e066f6cfdee9dc70768d',
    messagingSenderId: '416175352696',
    projectId: 'smart-ride-app-c77ee',
    authDomain: 'smart-ride-app-c77ee.firebaseapp.com',
    storageBucket: 'smart-ride-app-c77ee.firebasestorage.app',
    measurementId: 'G-Q2JLN73ZWC',
  );
}
